nginx:
  enabled: true
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: localhost
      # Different clouds or configurations might need /* as the default path
      path: /
      backend:
        name: sonarqube-sonarqube
        port:
          number: 9000
          protocol: HTTP
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"