nginx:
  enabled: true
ingress:
  enabled: true
  hosts:
    - name: localhost
      path: /
      backend:
        name: sonarqube-sonarqube
        port:
          number: 9000
          protocol: HTTP
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"


env:
- name: sonar.web.javaAdditionalOpts
  value: -javaagent:/opt/sonarqube/extensions/downloads/sonarqube-community-branch-plugin-1.11.0.jar=web
- name: sonar.ce.javaAdditionalOpts
  value: -javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.11.0.jar=ce